# Numpy
* Numerical python or numeric python.
* Numpy is a programming language that deals with multi-dimensional arrays and matrices.
* numpy supports a large number of mathematical operations

# Why use Numpy
* Numpy is memory efficiency,meaning it can handle the vast amount of data more accesible than any other library
* especially for matrix multiplication and reshaping.
* on top of that,Numpy is fast. In fact, TensorFlow and Scikit.


# How to Install Numpy
* Numpy is installed by default in anaconda

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.19.2


In [4]:
import numpy as np
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [10]:
data =np.array([[1,2,3,4,9],[5,6,7,8,10]])
print(np.shape(data))
print(data.dtype)

(2, 5)
int32


In [12]:
a1=np.array([2,4,6,8,])
a2=np.array([3,5,7,9])
print(a1+a2)
print(a1-a2)

[ 5  9 13 17]
[-1 -1 -1 -1]


In [35]:
data=np.array([[1.1,2.2,3.3,4.5],[5.5,6.6,7.7,8.8]])
print(np.shape(data))
print(data.dtype)
print(data)
print(data.reshape(4,2))
data.flatten()

(2, 4)
float64
[[1.1 2.2 3.3 4.4]
 [5.5 6.6 7.7 8.8]]
[[1.1 2.2]
 [3.3 4.4]
 [5.5 6.6]
 [7.7 8.8]]


array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8])

In [30]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [37]:
np.hstack((a1,a2))

array([2, 4, 6, 8, 3, 5, 7, 9])

In [40]:
np.vstack((a1,a2))

array([[2, 4, 6, 8],
       [3, 5, 7, 9]])

In [81]:
print(data.sum())
print(data.mean())
print(np.median(data))
print(data.std())       #standard deviation
np.mod(5,9)

39.6
4.95
4.95
2.520416632225712


5

In [65]:
d=np.random.randint(1,3,(3,3))
print(d)

[[1 1 2]
 [2 2 2]
 [1 1 1]]


In [91]:
np.random.normal(1,3,5)

array([ 2.91271373, -1.64607628,  0.34397259,  3.05853404, -6.10799826])

In [82]:
print(a1.dot(a2))

140


In [87]:
np.array([a2,pow(a2,3)])

array([[  3,   5,   7,   9],
       [ 27, 125, 343, 729]])

In [89]:
np.repeat([1,2,3,4],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [90]:
np.diag(a1)

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [107]:
n=int(input())
np.arange(0,n,2)

10


array([0, 2, 4, 6, 8])

In [110]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])